### ISSUE TITLE
(not really an issue) will reclaimed rocks get 1.19.2 support?

### ISSUE THREAD

**Issue by GodzillaFan13** [Subthy/Forge-1.20.1-create-reclaimed-rocks#1]
just leaving this question here because i am curious on the subject, and i know many people don't use 1.19.4 for modded, especially on forge.

**Comment by Subthy** [comment]
Looking at how much I need to do for the backport from 1.19.4 to 1.19.2. I doubt I will do it, as a lot of changes are made between those versions. I would need to rewrite more then half of the code. I might do it in far future, if I have nothing to do, but not right now.
