### ISSUE TITLE
Gabbro/Weathered Limestone Fancy Brick Slabs (including double slabs) do not break faster or drop anything when mined with a pickaxe

### ISSUE THREAD

**Issue by Dovahbear99** [Subthy/Forge-1.20.1-create-reclaimed-rocks#2]
When mining these blocks with a pickaxe, they will behave as if you are mining them by hand, taking a long time to break and dropping nothing. Does not occur with the dolomite variant. May possibly occur with some other blocks, but I have not tested all of them.

**Comment by Subthy** [comment]
I see. I'll have a look at this later today

**Comment by Subthy** [comment]
Found the issue. Will be releasing an update today to fix it.
